services:
  - type: worker
    name: climate-telegram-bot
    runtime: python
    repo: https://github.com/Rohithcr02/RAG-climate
    branch: telegram_endpoint
    buildCommand: pip install -r requirements_contextual.txt
    startCommand: python telegram_bot_contextual.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: CONTEXTUAL_API_KEY
        sync: false
      - key: CONTEXTUAL_AGENT_ID
        sync: false
